// Code generated by make codegen DO NOT EDIT.
// source: lib/column/codegen/array.tpl

package column

// appendRowPlain is a reflection-free realisation of append for plain arrays.
func (col *Array) appendRowPlain(v any) error { _ = "STUB: not implemented"; return nil }
