// Code generated by make codegen DO NOT EDIT.
// source: lib/column/codegen/column.tpl

package column

import (
	"math/big"
	"net"
	"reflect"
	"time"

	"github.com/ClickHouse/ch-go/proto"
	"github.com/ClickHouse/clickhouse-go/v2/lib/chcol"
	"github.com/google/uuid"
	"github.com/paulmach/orb"
	"github.com/shopspring/decimal"
)

func (t Type) Column(name string, sc *ServerContext) (Interface, error) {
	_ = "STUB: not implemented"
	return *new(Interface), nil
}

type (
	BFloat16 struct {
		name string
		col  proto.ColBFloat16
	}
	Float32 struct {
		name string
		col  proto.ColFloat32
	}
	Float64 struct {
		name string
		col  proto.ColFloat64
	}
	Int8 struct {
		name string
		col  proto.ColInt8
	}
	Int16 struct {
		name string
		col  proto.ColInt16
	}
	Int32 struct {
		name string
		col  proto.ColInt32
	}
	Int64 struct {
		name string
		col  proto.ColInt64
	}
	UInt8 struct {
		name string
		col  proto.ColUInt8
	}
	UInt16 struct {
		name string
		col  proto.ColUInt16
	}
	UInt32 struct {
		name string
		col  proto.ColUInt32
	}
	UInt64 struct {
		name string
		col  proto.ColUInt64
	}
)

var (
	_ Interface = (*BFloat16)(nil)
	_ Interface = (*Float32)(nil)
	_ Interface = (*Float64)(nil)
	_ Interface = (*Int8)(nil)
	_ Interface = (*Int16)(nil)
	_ Interface = (*Int32)(nil)
	_ Interface = (*Int64)(nil)
	_ Interface = (*UInt8)(nil)
	_ Interface = (*UInt16)(nil)
	_ Interface = (*UInt32)(nil)
	_ Interface = (*UInt64)(nil)
	_ Interface = (*Time)(nil)
	_ Interface = (*Time64)(nil)
)

var (
	scanTypeBFloat16        = reflect.TypeOf(float32(0))
	scanTypeFloat32         = reflect.TypeOf(float32(0))
	scanTypeFloat64         = reflect.TypeOf(float64(0))
	scanTypeInt8            = reflect.TypeOf(int8(0))
	scanTypeInt16           = reflect.TypeOf(int16(0))
	scanTypeInt32           = reflect.TypeOf(int32(0))
	scanTypeInt64           = reflect.TypeOf(int64(0))
	scanTypeUInt8           = reflect.TypeOf(uint8(0))
	scanTypeUInt16          = reflect.TypeOf(uint16(0))
	scanTypeUInt32          = reflect.TypeOf(uint32(0))
	scanTypeUInt64          = reflect.TypeOf(uint64(0))
	scanTypeIP              = reflect.TypeOf(net.IP{})
	scanTypeBool            = reflect.TypeOf(true)
	scanTypeByte            = reflect.TypeOf([]byte{})
	scanTypeUUID            = reflect.TypeOf(uuid.UUID{})
	scanTypeTime            = reflect.TypeOf(time.Time{})
	scanTypeDuration        = reflect.TypeOf(time.Duration(0))
	scanTypeRing            = reflect.TypeOf(orb.Ring{})
	scanTypePoint           = reflect.TypeOf(orb.Point{})
	scanTypeSlice           = reflect.TypeOf([]any{})
	scanTypeMap             = reflect.TypeOf(map[string]any{})
	scanTypeBigInt          = reflect.TypeOf(&big.Int{})
	scanTypeString          = reflect.TypeOf("")
	scanTypePolygon         = reflect.TypeOf(orb.Polygon{})
	scanTypeDecimal         = reflect.TypeOf(decimal.Decimal{})
	scanTypeMultiPolygon    = reflect.TypeOf(orb.MultiPolygon{})
	scanTypeLineString      = reflect.TypeOf(orb.LineString{})
	scanTypeMultiLineString = reflect.TypeOf(orb.MultiLineString{})
	scanTypeVariant         = reflect.TypeOf(chcol.Variant{})
	scanTypeDynamic         = reflect.TypeOf(chcol.Dynamic{})
	scanTypeJSON            = reflect.TypeOf(chcol.JSON{})
	scanTypeJSONString      = reflect.TypeOf("")
)

func (col *BFloat16) Name() string { _ = "STUB: not implemented"; return "" }

func (col *BFloat16) Type() Type { _ = "STUB: not implemented"; return *new(Type) }

func (col *BFloat16) ScanType() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (col *BFloat16) Rows() int { _ = "STUB: not implemented"; return 0 }

func (col *BFloat16) Reset() { _ = "STUB: not implemented"; return }

func (col *BFloat16) ScanRow(dest any, row int) error { _ = "STUB: not implemented"; return nil }

func (col *BFloat16) Row(i int, ptr bool) any { _ = "STUB: not implemented"; return *new(any) }

func (col *BFloat16) Append(v any) (nulls []uint8, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (col *BFloat16) AppendRow(v any) error { _ = "STUB: not implemented"; return nil }

func (col *BFloat16) Decode(reader *proto.Reader, rows int) error {
	_ = "STUB: not implemented"
	return nil
}

func (col *BFloat16) Encode(buffer *proto.Buffer) { _ = "STUB: not implemented"; return }

func (col *Float32) Name() string { _ = "STUB: not implemented"; return "" }

func (col *Float32) Type() Type { _ = "STUB: not implemented"; return *new(Type) }

func (col *Float32) ScanType() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (col *Float32) Rows() int { _ = "STUB: not implemented"; return 0 }

func (col *Float32) Reset() { _ = "STUB: not implemented"; return }

func (col *Float32) ScanRow(dest any, row int) error { _ = "STUB: not implemented"; return nil }

func (col *Float32) Row(i int, ptr bool) any { _ = "STUB: not implemented"; return *new(any) }

func (col *Float32) Append(v any) (nulls []uint8, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (col *Float32) AppendRow(v any) error { _ = "STUB: not implemented"; return nil }

func (col *Float32) Decode(reader *proto.Reader, rows int) error {
	_ = "STUB: not implemented"
	return nil
}

func (col *Float32) Encode(buffer *proto.Buffer) { _ = "STUB: not implemented"; return }

func (col *Float64) Name() string { _ = "STUB: not implemented"; return "" }

func (col *Float64) Type() Type { _ = "STUB: not implemented"; return *new(Type) }

func (col *Float64) ScanType() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (col *Float64) Rows() int { _ = "STUB: not implemented"; return 0 }

func (col *Float64) Reset() { _ = "STUB: not implemented"; return }

func (col *Float64) ScanRow(dest any, row int) error { _ = "STUB: not implemented"; return nil }

func (col *Float64) Row(i int, ptr bool) any { _ = "STUB: not implemented"; return *new(any) }

func (col *Float64) Append(v any) (nulls []uint8, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (col *Float64) AppendRow(v any) error { _ = "STUB: not implemented"; return nil }

func (col *Float64) Decode(reader *proto.Reader, rows int) error {
	_ = "STUB: not implemented"
	return nil
}

func (col *Float64) Encode(buffer *proto.Buffer) { _ = "STUB: not implemented"; return }

func (col *Int8) Name() string { _ = "STUB: not implemented"; return "" }

func (col *Int8) Type() Type { _ = "STUB: not implemented"; return *new(Type) }

func (col *Int8) ScanType() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (col *Int8) Rows() int { _ = "STUB: not implemented"; return 0 }

func (col *Int8) Reset() { _ = "STUB: not implemented"; return }

func (col *Int8) ScanRow(dest any, row int) error { _ = "STUB: not implemented"; return nil }

func (col *Int8) Row(i int, ptr bool) any { _ = "STUB: not implemented"; return *new(any) }

func (col *Int8) Append(v any) (nulls []uint8, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (col *Int8) AppendRow(v any) error { _ = "STUB: not implemented"; return nil }

func (col *Int8) Decode(reader *proto.Reader, rows int) error {
	_ = "STUB: not implemented"
	return nil
}

func (col *Int8) Encode(buffer *proto.Buffer) { _ = "STUB: not implemented"; return }

func (col *Int16) Name() string { _ = "STUB: not implemented"; return "" }

func (col *Int16) Type() Type { _ = "STUB: not implemented"; return *new(Type) }

func (col *Int16) ScanType() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (col *Int16) Rows() int { _ = "STUB: not implemented"; return 0 }

func (col *Int16) Reset() { _ = "STUB: not implemented"; return }

func (col *Int16) ScanRow(dest any, row int) error { _ = "STUB: not implemented"; return nil }

func (col *Int16) Row(i int, ptr bool) any { _ = "STUB: not implemented"; return *new(any) }

func (col *Int16) Append(v any) (nulls []uint8, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (col *Int16) AppendRow(v any) error { _ = "STUB: not implemented"; return nil }

func (col *Int16) Decode(reader *proto.Reader, rows int) error {
	_ = "STUB: not implemented"
	return nil
}

func (col *Int16) Encode(buffer *proto.Buffer) { _ = "STUB: not implemented"; return }

func (col *Int32) Name() string { _ = "STUB: not implemented"; return "" }

func (col *Int32) Type() Type { _ = "STUB: not implemented"; return *new(Type) }

func (col *Int32) ScanType() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (col *Int32) Rows() int { _ = "STUB: not implemented"; return 0 }

func (col *Int32) Reset() { _ = "STUB: not implemented"; return }

func (col *Int32) ScanRow(dest any, row int) error { _ = "STUB: not implemented"; return nil }

func (col *Int32) Row(i int, ptr bool) any { _ = "STUB: not implemented"; return *new(any) }

func (col *Int32) Append(v any) (nulls []uint8, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (col *Int32) AppendRow(v any) error { _ = "STUB: not implemented"; return nil }

func (col *Int32) Decode(reader *proto.Reader, rows int) error {
	_ = "STUB: not implemented"
	return nil
}

func (col *Int32) Encode(buffer *proto.Buffer) { _ = "STUB: not implemented"; return }

func (col *Int64) Name() string { _ = "STUB: not implemented"; return "" }

func (col *Int64) Type() Type { _ = "STUB: not implemented"; return *new(Type) }

func (col *Int64) ScanType() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (col *Int64) Rows() int { _ = "STUB: not implemented"; return 0 }

func (col *Int64) Reset() { _ = "STUB: not implemented"; return }

func (col *Int64) ScanRow(dest any, row int) error { _ = "STUB: not implemented"; return nil }

func (col *Int64) Row(i int, ptr bool) any { _ = "STUB: not implemented"; return *new(any) }

func (col *Int64) Append(v any) (nulls []uint8, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (col *Int64) AppendRow(v any) error { _ = "STUB: not implemented"; return nil }

func (col *Int64) Decode(reader *proto.Reader, rows int) error {
	_ = "STUB: not implemented"
	return nil
}

func (col *Int64) Encode(buffer *proto.Buffer) { _ = "STUB: not implemented"; return }

func (col *UInt8) Name() string { _ = "STUB: not implemented"; return "" }

func (col *UInt8) Type() Type { _ = "STUB: not implemented"; return *new(Type) }

func (col *UInt8) ScanType() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (col *UInt8) Rows() int { _ = "STUB: not implemented"; return 0 }

func (col *UInt8) Reset() { _ = "STUB: not implemented"; return }

func (col *UInt8) ScanRow(dest any, row int) error { _ = "STUB: not implemented"; return nil }

func (col *UInt8) Row(i int, ptr bool) any { _ = "STUB: not implemented"; return *new(any) }

func (col *UInt8) Append(v any) (nulls []uint8, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (col *UInt8) AppendRow(v any) error { _ = "STUB: not implemented"; return nil }

func (col *UInt8) Decode(reader *proto.Reader, rows int) error {
	_ = "STUB: not implemented"
	return nil
}

func (col *UInt8) Encode(buffer *proto.Buffer) { _ = "STUB: not implemented"; return }

func (col *UInt16) Name() string { _ = "STUB: not implemented"; return "" }

func (col *UInt16) Type() Type { _ = "STUB: not implemented"; return *new(Type) }

func (col *UInt16) ScanType() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (col *UInt16) Rows() int { _ = "STUB: not implemented"; return 0 }

func (col *UInt16) Reset() { _ = "STUB: not implemented"; return }

func (col *UInt16) ScanRow(dest any, row int) error { _ = "STUB: not implemented"; return nil }

func (col *UInt16) Row(i int, ptr bool) any { _ = "STUB: not implemented"; return *new(any) }

func (col *UInt16) Append(v any) (nulls []uint8, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (col *UInt16) AppendRow(v any) error { _ = "STUB: not implemented"; return nil }

func (col *UInt16) Decode(reader *proto.Reader, rows int) error {
	_ = "STUB: not implemented"
	return nil
}

func (col *UInt16) Encode(buffer *proto.Buffer) { _ = "STUB: not implemented"; return }

func (col *UInt32) Name() string { _ = "STUB: not implemented"; return "" }

func (col *UInt32) Type() Type { _ = "STUB: not implemented"; return *new(Type) }

func (col *UInt32) ScanType() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (col *UInt32) Rows() int { _ = "STUB: not implemented"; return 0 }

func (col *UInt32) Reset() { _ = "STUB: not implemented"; return }

func (col *UInt32) ScanRow(dest any, row int) error { _ = "STUB: not implemented"; return nil }

func (col *UInt32) Row(i int, ptr bool) any { _ = "STUB: not implemented"; return *new(any) }

func (col *UInt32) Append(v any) (nulls []uint8, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (col *UInt32) AppendRow(v any) error { _ = "STUB: not implemented"; return nil }

func (col *UInt32) Decode(reader *proto.Reader, rows int) error {
	_ = "STUB: not implemented"
	return nil
}

func (col *UInt32) Encode(buffer *proto.Buffer) { _ = "STUB: not implemented"; return }

func (col *UInt64) Name() string { _ = "STUB: not implemented"; return "" }

func (col *UInt64) Type() Type { _ = "STUB: not implemented"; return *new(Type) }

func (col *UInt64) ScanType() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (col *UInt64) Rows() int { _ = "STUB: not implemented"; return 0 }

func (col *UInt64) Reset() { _ = "STUB: not implemented"; return }

func (col *UInt64) ScanRow(dest any, row int) error { _ = "STUB: not implemented"; return nil }

func (col *UInt64) Row(i int, ptr bool) any { _ = "STUB: not implemented"; return *new(any) }

func (col *UInt64) Append(v any) (nulls []uint8, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (col *UInt64) AppendRow(v any) error { _ = "STUB: not implemented"; return nil }

func (col *UInt64) Decode(reader *proto.Reader, rows int) error {
	_ = "STUB: not implemented"
	return nil
}

func (col *UInt64) Encode(buffer *proto.Buffer) { _ = "STUB: not implemented"; return }
